; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; --- 烧录与串口设置 ---
monitor_speed = 115200
upload_speed = 921600 ;烧录速度

; --- ESP32-S3-WROOM-1-N16R8
;16MB Flash模块
board_upload.flash_size = 16MB
;告诉 Arduino Core 使用 Octal SPI OPI Flash
board_build.arduino.memory_type = qio_opi
;激活外部 PSRAM（模块有 8MB）否则 LVGL 内存不够 → Guru panic
build_flags =
    -DBOARD_HAS_PSRAM
    ;这是官方补丁,不加这个会发生随机崩溃（特别是大图像渲染时）
    -mfix-esp32-psram-cache-issue
;让 LVGL 在包含配置文件时使用简单路径，如 #include "lv_conf.h"
    -D LV_CONF_INCLUDE_SIMPLE
;把 src/ 目录加入编译器头文件搜索路径，让 LVGL 能找到 lv_conf.h
    -I src
;告诉 TFT_eSPI 库：不要加载库自带的配置文件，用在 platformio.ini 里定义的参数！
    -D USER_SETUP_LOADED=1
    -D ST7796_DRIVER=1
    ; 定义屏幕分辨率
    -D TFT_WIDTH=320
    -D TFT_HEIGHT=480

    ;激活 SPI 总线
    -D USE_FSPI_PORT
    -D USE_HSPI_PORT
;让 TFT_eSPI 使用 HSPI 对应的硬件 SPI 控制器（SPI2_HOST） 
    -D TFT_SPI_HOST=HSPI

    ; 定义 SPI 引脚 
    -D TFT_MISO=46
    -D TFT_MOSI=11
    -D TFT_SCLK=12
    -D TFT_CS=10
    -D TFT_DC=7
    -D TFT_RST=6
    -D TFT_BL=5
    -D TFT_BACKLIGHT_ON=1
    -D TOUCH_CS=-1   ; 禁用库自带触摸，防止冲突

    ; 其它设置
    -D LOAD_GLCD=1
    -D LOAD_FONT2=1
    -D LOAD_FONT4=1
    -D SPI_FREQUENCY=40000000  ; SPI 速度 40MHz
    -D SPI_READ_FREQUENCY=20000000

; --- 自动下载库 ---
lib_deps =
    bodmer/TFT_eSPI @ 2.5.43
    lvgl/lvgl @ 8.3.11 
    ESP32Async/ESPAsyncWebServer
    esp32async/AsyncTCP